apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-simple-app
  name: go-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-simple-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-simple-app
    spec:
      containers:
      - image: acehanks/go-simple-app:v1
        name: go-simple-app
        resources: {}
status: {}
